export interface WordPair { category: string; civilian: string; impostor: string; }
// Lista unificada de parejas (~250) - fuente principal para selección de palabras
export const wordPairs: WordPair[] = [
  { category: 'Lugares', civilian: 'piscina', impostor: 'playa' },
  { category: 'Salud', civilian: 'hospital', impostor: 'farmacia' },
  { category: 'Comida', civilian: 'tortilla', impostor: 'arepa' },
  { category: 'Gastronomía Nica', civilian: 'Gallo pinto', impostor: 'Arroz con frijoles' },
  { category: 'Gastronomía Nica', civilian: 'Nacatamal', impostor: 'Tamal pisque' },
  { category: 'Gastronomía Nica', civilian: 'Vigorón', impostor: 'Baho' },
  { category: 'Gastronomía Nica', civilian: 'Quesillo', impostor: 'Güirila con cuajada' },
  { category: 'Gastronomía Nica', civilian: 'Rosquillas somoteñas', impostor: 'Viejitas' },
  { category: 'Gastronomía Nica', civilian: 'Pinolillo', impostor: 'Cacao con leche' },
  { category: 'Gastronomía Nica', civilian: 'Sopa de queso', impostor: 'Sopa de mondongo' },
  { category: 'Gastronomía Nica', civilian: 'Tostones', impostor: 'Maduros fritos' },
  { category: 'Gastronomía Nica', civilian: 'Carne asada de fritanga', impostor: 'Pollo asado' },
  { category: 'Gastronomía Nica', civilian: 'Cajeta de coco', impostor: 'Manjar de leche' },

  { category: 'Lugares de Nicaragua', civilian: 'Isla de Ometepe', impostor: 'Corn Island' },
  { category: 'Lugares de Nicaragua', civilian: 'Catedral de León', impostor: 'Antigua Catedral de Managua' },
  { category: 'Lugares de Nicaragua', civilian: 'Mercado Oriental', impostor: 'Mercado Roberto Huembes' },
  { category: 'Lugares de Nicaragua', civilian: 'Volcán Masaya', impostor: 'Volcán Cerro Negro' },
  { category: 'Lugares de Nicaragua', civilian: 'Cañón de Somoto', impostor: 'Laguna de Apoyo' },
  { category: 'Lugares de Nicaragua', civilian: 'Puerto Salvador Allende', impostor: 'Paseo Xolotlán' },
  { category: 'Lugares de Nicaragua', civilian: 'San Juan del Sur', impostor: 'Pochomil' },
  { category: 'Lugares de Nicaragua', civilian: 'Granada', impostor: 'León' },
  { category: 'Lugares de Nicaragua', civilian: 'Mirador de Catarina', impostor: 'El Crucero' },
  { category: 'Lugares de Nicaragua', civilian: 'Río San Juan', impostor: 'Lago Cocibolca' },

  { category: 'Famosos', civilian: 'Rubén Darío', impostor: 'Gabriel García Márquez' },
  { category: 'Famosos', civilian: 'Alexis Argüello', impostor: 'Chocolatito González' },
  { category: 'Famosos', civilian: 'Shakira', impostor: 'Karol G' },
  { category: 'Famosos', civilian: 'Lionel Messi', impostor: 'Cristiano Ronaldo' },
  { category: 'Famosos', civilian: 'Carlos Mejía Godoy', impostor: 'Luis Enrique (Salsero)' },
  { category: 'Famosos', civilian: 'Elon Musk', impostor: 'Mark Zuckerberg' },
  { category: 'Famosos', civilian: 'El Papa Francisco', impostor: 'Dalai Lama' },
  { category: 'Famosos', civilian: 'Taylor Swift', impostor: 'Beyoncé' },
  { category: 'Famosos', civilian: 'Sheynnis Palacios', impostor: 'Xiomara Blandino' },
  { category: 'Famosos', civilian: 'Bad Bunny', impostor: 'Daddy Yankee' },

  { category: 'Vida Cotidiana', civilian: 'Caponera', impostor: 'Taxi' },
  { category: 'Vida Cotidiana', civilian: 'Pulpería', impostor: 'Minisúper' },
  { category: 'Vida Cotidiana', civilian: 'Hamaca', impostor: 'Sillón mecedora' },
  { category: 'Vida Cotidiana', civilian: 'Abanico de pedestal', impostor: 'Aire acondicionado' },
  { category: 'Vida Cotidiana', civilian: 'Chinelas de hule', impostor: 'Sandalias de cuero' },
  { category: 'Vida Cotidiana', civilian: 'Ruta (Bus urbano)', impostor: 'Interlocal' },
  { category: 'Vida Cotidiana', civilian: 'Balde con agua', impostor: 'Barril con agua' },
  { category: 'Vida Cotidiana', civilian: 'Machete', impostor: 'Hacha' },
  { category: 'Vida Cotidiana', civilian: 'Cauce', impostor: 'Río' },
  { category: 'Vida Cotidiana', civilian: 'Pacas de ropa usada', impostor: 'Tienda por departamentos' },

  { category: 'Entretenimiento y Ficción', civilian: 'El Chavo del 8', impostor: 'Cantinflas' },
  { category: 'Entretenimiento y Ficción', civilian: 'Harry Potter', impostor: 'Frodo Bolsón' },
  { category: 'Entretenimiento y Ficción', civilian: 'Netflix', impostor: 'YouTube' },
  { category: 'Entretenimiento y Ficción', civilian: 'TikTok', impostor: 'Instagram Reels' },
  { category: 'Entretenimiento y Ficción', civilian: 'La Llorona', impostor: 'La Mocuana' },
  { category: 'Entretenimiento y Ficción', civilian: 'El Cadejo Negro', impostor: 'El Padre sin Cabeza' },
  { category: 'Entretenimiento y Ficción', civilian: 'Batman', impostor: 'Iron Man' },
  { category: 'Entretenimiento y Ficción', civilian: 'Star Wars', impostor: 'Star Trek' },
  { category: 'Entretenimiento y Ficción', civilian: 'El Güegüense', impostor: 'Baile de Negras' },
  { category: 'Entretenimiento y Ficción', civilian: 'Telenovela', impostor: 'Serie de televisión' },

  { category: 'Naturaleza y Animales', civilian: 'Guardabarranco', impostor: 'Zanate' },
  { category: 'Naturaleza y Animales', civilian: 'Chojoyo', impostor: 'Lora nuca amarilla' },
  { category: 'Naturaleza y Animales', civilian: 'Mono Congo', impostor: 'Mico (Cara blanca)' },
  { category: 'Naturaleza y Animales', civilian: 'Árbol de Sacuanjoche', impostor: 'Árbol de Madroño' },
  { category: 'Naturaleza y Animales', civilian: 'Zancudo', impostor: 'Mosca' },
  { category: 'Naturaleza y Animales', civilian: 'Perro aguacatero', impostor: 'Perro de raza' },
  { category: 'Naturaleza y Animales', civilian: 'Garrobo', impostor: 'Iguana' },
  { category: 'Naturaleza y Animales', civilian: 'Tiburón', impostor: 'Delfín' },
  { category: 'Naturaleza y Animales', civilian: 'Caballo', impostor: 'Burro' },
  { category: 'Naturaleza y Animales', civilian: 'Jícaro', impostor: 'Cuductero' },

  { category: 'Tradiciones y Eventos', civilian: 'La Purísima', impostor: 'La Gritería' },
  { category: 'Tradiciones y Eventos', civilian: 'Fiestas de Santo Domingo', impostor: 'Fiestas de San Jerónimo' },
  { category: 'Tradiciones y Eventos', civilian: 'Semana Santa', impostor: 'Vacaciones de Verano' },
  { category: 'Tradiciones y Eventos', civilian: 'Piñata', impostor: 'Pastel de cumpleaños' },
  { category: 'Tradiciones y Eventos', civilian: 'Desfile Hípico', impostor: 'Corrida de toros' },
  { category: 'Tradiciones y Eventos', civilian: 'Boda civil', impostor: 'Boda eclesiástica' },
  { category: 'Tradiciones y Eventos', civilian: 'Rezar el novenario', impostor: 'Ir a misa' },
  { category: 'Tradiciones y Eventos', civilian: 'Aguinaldo', impostor: 'Bono salarial' },
  { category: 'Tradiciones y Eventos', civilian: 'Promoción de Bachiller', impostor: 'Graduación de Universidad' },
  { category: 'Tradiciones y Eventos', civilian: 'Velorio', impostor: 'Entierro' },

  { category: 'Objetos y Tecnología', civilian: 'Laptop', impostor: 'Tablet' },
  { category: 'Objetos y Tecnología', civilian: 'Cargador de celular', impostor: 'Power bank' },
  { category: 'Objetos y Tecnología', civilian: 'Cédula de identidad', impostor: 'Licencia de conducir' },
  { category: 'Objetos y Tecnología', civilian: 'Llaves de la casa', impostor: 'Control del portón' },
  { category: 'Objetos y Tecnología', civilian: 'Silla plástica', impostor: 'Banco de madera' },
  { category: 'Objetos y Tecnología', civilian: 'Escoba', impostor: 'Lampazo' },
  { category: 'Objetos y Tecnología', civilian: 'Paila', impostor: 'Olla arrocera' },
  { category: 'Objetos y Tecnología', civilian: 'Fósforos', impostor: 'Encendedor' },
  { category: 'Objetos y Tecnología', civilian: 'Jabón de lavar trastes', impostor: 'Detergente en polvo' },
  { category: 'Objetos y Tecnología', civilian: 'Auriculares', impostor: 'Parlante Bluetooth' },

  { category: 'Conceptos y Acciones', civilian: 'Pedir fiado', impostor: 'Pedir prestado' },
  { category: 'Conceptos y Acciones', civilian: 'Chisme', impostor: 'Secreto' },
  { category: 'Conceptos y Acciones', civilian: 'Calor húmedo', impostor: 'Calor seco' },
  { category: 'Conceptos y Acciones', civilian: 'Madrugar', impostor: 'Desvelarse' },
  { category: 'Conceptos y Acciones', civilian: 'Ahorrar', impostor: 'Gastar con cuidado' },
  { category: 'Conceptos y Acciones', civilian: 'Salir a bacanalear', impostor: 'Salir a cenar' },
  { category: 'Conceptos y Acciones', civilian: 'Estudiar', impostor: 'Hacer la tarea' },
  { category: 'Conceptos y Acciones', civilian: 'Lluvia fuerte', impostor: 'Temporal' },
  { category: 'Conceptos y Acciones', civilian: 'Tener hambre', impostor: 'Tener antojo' },
  { category: 'Conceptos y Acciones', civilian: 'Llegar tarde', impostor: 'No llegar' },

  { category: 'Bebidas y Ocio', civilian: 'Cerveza Toña', impostor: 'Cerveza Victoria' },
  { category: 'Bebidas y Ocio', civilian: 'Ron Flor de Caña', impostor: 'Ron Plata' },
  { category: 'Bebidas y Ocio', civilian: 'Café negro', impostor: 'Café con leche' },
  { category: 'Bebidas y Ocio', civilian: 'Refresco de Rojo (Milca)', impostor: 'Kola Shaler' },
  { category: 'Bebidas y Ocio', civilian: 'Agua en bolsa', impostor: 'Botella de agua' },
  { category: 'Bebidas y Ocio', civilian: 'Ir al estadio', impostor: 'Ver el partido en TV' },
  { category: 'Bebidas y Ocio', civilian: 'Jugar naipe', impostor: 'Jugar dominó' },
  { category: 'Bebidas y Ocio', civilian: 'Guitarra acústica', impostor: 'Ukelele' },
  { category: 'Bebidas y Ocio', civilian: 'Cine', impostor: 'Teatro' },
  { category: 'Bebidas y Ocio', civilian: 'Piscina inflable', impostor: 'Manguerazo en el patio' },

  // --- GASTRONOMÍA Y BEBIDAS ---
  { category: 'Comida Nica', civilian: 'Indio Viejo', impostor: 'Masa de cazuela' },
  { category: 'Comida Nica', civilian: 'Chancho con yuca', impostor: 'Vigorón' },
  { category: 'Comida Nica', civilian: 'Tortilla de maíz', impostor: 'Güirila' },
  { category: 'Comida Nica', civilian: 'Queso frito', impostor: 'Queso asado' },
  { category: 'Comida Nica', civilian: 'Ensalada de repollo', impostor: 'Pico de gallo' },
  { category: 'Comida Nica', civilian: 'Chicha de maíz', impostor: 'Fresco de Cacao' },
  { category: 'Comida Nica', civilian: 'Fresco de Cebada', impostor: 'Semilla de Jícaro' },
  { category: 'Comida Nica', civilian: 'Pio Quinto', impostor: 'Sopa borracha' },
  { category: 'Comida Nica', civilian: 'Ayote en miel', impostor: 'Almíbar' },
  { category: 'Comida Nica', civilian: 'Tajadas verdes', impostor: 'Tajadas maduras' },
  { category: 'Comida Nica', civilian: 'Carne desmenuzada', impostor: 'Salpicón' },
  { category: 'Comida Nica', civilian: 'Sopa de res', impostor: 'Sopa de costilla alta' },
  { category: 'Comida Nica', civilian: 'Pescado frito', impostor: 'Filete de pescado' },
  { category: 'Comida Nica', civilian: 'Rondón', impostor: 'Sopa de mariscos' },
  { category: 'Comida Nica', civilian: 'Pan de coco', impostor: 'Pico (Pan dulce)' },
  { category: 'Comida Internacional', civilian: 'Sushi', impostor: 'Ceviche' },
  { category: 'Comida Internacional', civilian: 'Tacos mexicanos', impostor: 'Burritos' },
  { category: 'Comida Internacional', civilian: 'Lasaña', impostor: 'Espagueti' },
  { category: 'Comida Rápida', civilian: 'Hot Dog', impostor: 'Hamburguesa' },
  { category: 'Comida Rápida', civilian: 'Papas fritas', impostor: 'Aros de cebolla' },
  { category: 'Desayuno', civilian: 'Huevo frito', impostor: 'Huevo revuelto' },
  { category: 'Desayuno', civilian: 'Lecheagria', impostor: 'Yogur natural' },
  { category: 'Dulces', civilian: 'Chocolate negro', impostor: 'Chocolate con leche' },
  { category: 'Dulces', civilian: 'Helado de cono', impostor: 'Paleta de hielo' },
  { category: 'Bebidas', civilian: 'Limonada', impostor: 'Naranjada' },

  // --- LUGARES Y GEOGRAFÍA (Nica & General) ---
  { category: 'Lugares Nica', civilian: 'Metrocentro', impostor: 'Galerías Santo Domingo' },
  { category: 'Lugares Nica', civilian: 'Multicentro Las Américas', impostor: 'Plaza Inter' },
  { category: 'Lugares Nica', civilian: 'Carretera a Masaya', impostor: 'Carretera Norte' },
  { category: 'Lugares Nica', civilian: 'Rotonda El Güegüense', impostor: 'Rotonda Jean Paul Genie' },
  { category: 'Lugares Nica', civilian: 'Universidad UCA', impostor: 'Universidad UNAN' },
  { category: 'Lugares Nica', civilian: 'Estadio Dennis Martínez', impostor: 'Polideportivo Alexis Argüello' },
  { category: 'Lugares Nica', civilian: 'Hospital Militar', impostor: 'Hospital Vivian Pellas' },
  { category: 'Lugares Nica', civilian: 'Playa Masachapa', impostor: 'Playa Pochomil' },
  { category: 'Lugares Nica', civilian: 'Playa Las Peñitas', impostor: 'Playa Poneloya' },
  { category: 'Lugares Nica', civilian: 'Isletas de Granada', impostor: 'Archipiélago de Solentiname' },
  { category: 'Lugares Nica', civilian: 'Reserva Bosawás', impostor: 'Reserva Indio Maíz' },
  { category: 'Lugares Nica', civilian: 'Mirador de Tiscapa', impostor: 'Loma de Tiscapa' },
  { category: 'Lugares', civilian: 'Cine VIP', impostor: 'Teatro Nacional' },
  { category: 'Lugares', civilian: 'Gimnasio', impostor: 'Parque de Calistenia' },
  { category: 'Lugares', civilian: 'Discoteca', impostor: 'Bar Lounge' },
  { category: 'Lugares', civilian: 'Zoológico', impostor: 'Refugio de animales' },
  { category: 'Lugares', civilian: 'Farmacia', impostor: 'Clínica' },
  { category: 'Lugares', civilian: 'Gasolinera', impostor: 'Taller mecánico' },
  { category: 'Lugares', civilian: 'Aeropuerto', impostor: 'Terminal de buses' },
  { category: 'Lugares', civilian: 'Iglesia', impostor: 'Catedral' },
  { category: 'Lugares', civilian: 'Piscina pública', impostor: 'Parque acuático' },
  { category: 'Lugares', civilian: 'Hotel', impostor: 'Airbnb / Hostal' },
  { category: 'Lugares', civilian: 'Museo de Arte', impostor: 'Galería de Arte' },
  { category: 'Lugares', civilian: 'Biblioteca', impostor: 'Librería' },
  { category: 'Lugares', civilian: 'Juzgados', impostor: 'Estación de Policía' },



  // --- ENTRETENIMIENTO Y CULTURA POP ---
  { category: 'Superhéroes', civilian: 'Superman', impostor: 'Capitán América' },
  { category: 'Superhéroes', civilian: 'Spiderman', impostor: 'Deadpool' },
  { category: 'Superhéroes', civilian: 'Joker', impostor: 'Harley Quinn' },
  { category: 'Superhéroes', civilian: 'Hulk', impostor: 'La Mole (Fantastic 4)' },
  { category: 'Superhéroes', civilian: 'Thor', impostor: 'Aquaman' },
  { category: 'Películas', civilian: 'Toy Story', impostor: 'Shrek' },
  { category: 'Películas', civilian: 'El Rey León', impostor: 'Madagascar' },
  { category: 'Películas', civilian: 'Titanic', impostor: 'El Diario de Noa' },
  { category: 'Películas', civilian: 'Rápidos y Furiosos', impostor: 'Misión Imposible' },
  { category: 'Películas', civilian: 'Jurassic Park', impostor: 'Godzilla' },
  { category: 'Música', civilian: 'Salsa', impostor: 'Merengue' },
  { category: 'Música', civilian: 'Reggaetón', impostor: 'Trap' },
  { category: 'Música', civilian: 'Rock', impostor: 'Metal' },
  { category: 'Música', civilian: 'Bachata', impostor: 'Vallenato' },
  { category: 'Música', civilian: 'Piano', impostor: 'Teclado electrónico' },
  { category: 'Música', civilian: 'Batería', impostor: 'Tambores' },
  { category: 'Música', civilian: 'Cantante', impostor: 'Rapero' },
  { category: 'Juegos', civilian: 'Ajedrez', impostor: 'Damas chinas' },
  { category: 'Juegos', civilian: 'Monopoly', impostor: 'Turista Mundial' },
  { category: 'Juegos', civilian: 'Rompecabezas', impostor: 'Lego' },
  { category: 'Juegos', civilian: 'Escondite', impostor: 'La lleva (Tag)' },
  { category: 'Deportes', civilian: 'Béisbol', impostor: 'Softbol' },
  { category: 'Deportes', civilian: 'Fútbol Campo', impostor: 'Fútbol Sala' },
  { category: 'Deportes', civilian: 'Baloncesto', impostor: 'Voleibol' },
  { category: 'Deportes', civilian: 'Tenis', impostor: 'Ping Pong' },
  { category: 'Deportes', civilian: 'Natación', impostor: 'Waterpolo' },
  { category: 'Deportes', civilian: 'Boxeo', impostor: 'Artes Marciales Mixtas (UFC)' },
  { category: 'Deportes', civilian: 'Ciclismo', impostor: 'Spinning' },
  { category: 'Deportes', civilian: 'Yoga', impostor: 'Pilates' },
  { category: 'Deportes', civilian: 'Maratón', impostor: 'Caminata' },


  // --- SECCIÓN ESPECIAL: LO NICA (Amplianda) ---
  { category: 'Lo Nica', civilian: 'El Güegüense', impostor: 'El Viejo y la Vieja' },
  { category: 'Lo Nica', civilian: 'Volcán Masaya (Lava)', impostor: 'Volcán Mombacho (Nubes)' },
  { category: 'Lo Nica', civilian: 'Laguna de Apoyo', impostor: 'Laguna de Xiloá' },
  { category: 'Lo Nica', civilian: 'Catedral de León', impostor: 'Palacio Nacional' },
  { category: 'Lo Nica', civilian: 'Rosquillas de Somoto', impostor: 'Cajetas de Masaya' },
  { category: 'Lo Nica', civilian: 'Nacatamal (Domingo)', impostor: 'Vaho (Fines de semana)' },
  { category: 'Lo Nica', civilian: 'Ir al Oriental (Caos)', impostor: 'Ir a Metrocentro (Paseo)' },
  { category: 'Lo Nica', civilian: 'Chocoyos del Volcán', impostor: 'Monos del Zoológico' },
  { category: 'Lo Nica', civilian: 'Beisbol en el Dennis Martínez', impostor: 'Futbol en el Nacional' },
  { category: 'Lo Nica', civilian: 'Hacer la vaca (Colecta)', impostor: 'Invitar la ronda' },
  { category: 'Lo Nica', civilian: 'Chavalo (Niño)', impostor: 'Maje (Amigo/Joven)' },
  { category: 'Lo Nica', civilian: 'Fritanga de barrio', impostor: 'Comidería del mercado' },
  { category: 'Lo Nica', civilian: 'Puerto Salvador Allende', impostor: 'Malecón de Masaya' },
  { category: 'Lo Nica', civilian: 'Sopa de Mondongo', impostor: 'Sopa de Huevo de Toro' },
  { category: 'Lo Nica', civilian: 'Guardabarranco (Pájaro)', impostor: 'Sacuanjoche (Flor)' },
  { category: 'Lo Nica', civilian: 'La Purísima (Gritería)', impostor: 'Rezo del Niño Dios' },
  { category: 'Lo Nica', civilian: 'Pinol de Iguana', impostor: 'Indio Viejo' },
  { category: 'Lo Nica', civilian: 'Cacao helado', impostor: 'Grambicha (Fresco rojo)' },
  { category: 'Lo Nica', civilian: 'Chinelas Rolter', impostor: 'Zapatos Crocs' },
  { category: 'Lo Nica', civilian: 'Bus ruteado (Ruta)', impostor: 'Bus interlocales (Microbús)' },

  // --- TECNOLOGÍA Y MUNDO DIGITAL (Conceptos distintos pero relacionados) ---
  { category: 'Tecnología', civilian: 'Inteligencia Artificial', impostor: 'Realidad Virtual' },
  { category: 'Tecnología', civilian: 'Dron de video', impostor: 'Avión de papel' },
  { category: 'Tecnología', civilian: 'Impresora 3D', impostor: 'Máquina de coser' },
  { category: 'Tecnología', civilian: 'Criptomoneda (Bitcoin)', impostor: 'Billete de Lotería' },
  { category: 'Tecnología', civilian: 'Influencer de TikTok', impostor: 'Presentador de Noticias' },
  { category: 'Tecnología', civilian: 'Hacker', impostor: 'Detective privado' },
  { category: 'Tecnología', civilian: 'Podcast', impostor: 'Programa de Radio AM' },
  { category: 'Tecnología', civilian: 'Photoshop', impostor: 'Maquillaje real' },
  { category: 'Tecnología', civilian: 'Wikipedia', impostor: 'Enciclopedia de libros' },
  { category: 'Tecnología', civilian: 'Teclado Mecánico', impostor: 'Máquina de Escribir' },
  { category: 'Tecnología', civilian: 'Señal de Wifi', impostor: 'Hilo invisible' },
  { category: 'Tecnología', civilian: 'Smartwatch', impostor: 'Brújula' },
  { category: 'Tecnología', civilian: 'Satélite Espacial', impostor: 'Luna llena' },
  { category: 'Tecnología', civilian: 'Robot Aspiradora', impostor: 'Mascota (Perro)' },
  { category: 'Tecnología', civilian: 'Filtro de Instagram', impostor: 'Máscara de Carnaval' },

  // --- FANTASÍA, TERROR Y SCI-FI ---
  { category: 'Ficción', civilian: 'Máquina del Tiempo', impostor: 'Teletransportador' },
  { category: 'Ficción', civilian: 'Sable de Luz (Star Wars)', impostor: 'Varita Mágica (Harry Potter)' },
  { category: 'Ficción', civilian: 'Zombie (Muerto viviente)', impostor: 'Fantasma (Espíritu)' },
  { category: 'Ficción', civilian: 'Vampiro (Chupa sangre)', impostor: 'Mosquito (Zancudo)' },
  { category: 'Ficción', civilian: 'Dragón (Fuego)', impostor: 'Lanzallamas' },
  { category: 'Ficción', civilian: 'Superfuerza', impostor: 'Invisibilidad' },
  { category: 'Ficción', civilian: 'Ojo de Sauron', impostor: 'Cámara de vigilancia' },
  { category: 'Ficción', civilian: 'Escudo del Capitán América', impostor: 'Martillo de Thor' },
  { category: 'Ficción', civilian: 'La Matrix', impostor: 'Un Sueño Lúcido' },
  { category: 'Ficción', civilian: 'Godzilla', impostor: 'King Kong' },
  { category: 'Ficción', civilian: 'Sirena', impostor: 'Buzo profesional' },
  { category: 'Ficción', civilian: 'Centauro', impostor: 'Jinete a caballo' },
  { category: 'Ficción', civilian: 'Casa embrujada', impostor: 'Castillo abandonado' },
  { category: 'Ficción', civilian: 'Espejo mágico', impostor: 'Pantalla de celular' },
  { category: 'Ficción', civilian: 'Poción de amor', impostor: 'Perfume caro' },

  // --- OBJETOS DEL HOGAR (Funciones parecidas, formas distintas) ---
  { category: 'Hogar', civilian: 'Ventilador de techo', impostor: 'Helicóptero' },
  { category: 'Hogar', civilian: 'Lavadora', impostor: 'Licuadora' },
  { category: 'Hogar', civilian: 'Cuna de bebé', impostor: 'Jaula de mascota' },
  { category: 'Hogar', civilian: 'Inodoro', impostor: 'Trono real' },
  { category: 'Hogar', civilian: 'Ducha (Regadera)', impostor: 'Cascada natural' },
  { category: 'Hogar', civilian: 'Alfombra', impostor: 'Césped' },
  { category: 'Hogar', civilian: 'Cortina', impostor: 'Párpado' },
  { category: 'Hogar', civilian: 'Llave', impostor: 'Contraseña' },
  { category: 'Hogar', civilian: 'Basurero', impostor: 'Papelera de reciclaje (PC)' },
  { category: 'Hogar', civilian: 'Vela aromática', impostor: 'Barra de dinamita' },
  { category: 'Hogar', civilian: 'Sartén antiadherente', impostor: 'Raqueta de Tenis' },
  { category: 'Hogar', civilian: 'Almohada', impostor: 'Nube' },
  { category: 'Hogar', civilian: 'Espejo', impostor: 'Gemelo idéntico' },
  { category: 'Hogar', civilian: 'Escalera de mano', impostor: 'Ascensor' },
  { category: 'Hogar', civilian: 'Paraguas', impostor: 'Techo' },

  // --- COMIDA Y SABORES (Engañosos) ---
  { category: 'Comida', civilian: 'Sushi (Pescado crudo)', impostor: 'Taco (Carne cocida)' },
  { category: 'Comida', civilian: 'Huevo duro', impostor: 'Pelota de Golf' },
  { category: 'Comida', civilian: 'Espagueti', impostor: 'Gusanos de goma' },
  { category: 'Comida', civilian: 'Brocoli', impostor: 'Árbol pequeño (Bonsai)' },
  { category: 'Comida', civilian: 'Queso Suizo (Agujeros)', impostor: 'Esponja de baño' },
  { category: 'Comida', civilian: 'Chile picante', impostor: 'Fuego' },
  { category: 'Comida', civilian: 'Cocos', impostor: 'Bolas de Boliche' },
  { category: 'Comida', civilian: 'Pastel de cumpleaños', impostor: 'Piñata' },
  { category: 'Comida', civilian: 'Bebida energética', impostor: 'Café expreso' },
  { category: 'Comida', civilian: 'Algodón de azúcar', impostor: 'Telaraña' },
  { category: 'Comida', civilian: 'Palomitas de maíz', impostor: 'Granizo' },
  { category: 'Comida', civilian: 'Miel de abeja', impostor: 'Pegamento' },
  { category: 'Comida', civilian: 'Baguette (Pan largo)', impostor: 'Bate de beisbol' },

  // --- PROFESIONES Y ROLES (Conflicto de autoridad) ---
  { category: 'Roles', civilian: 'Árbitro de futbol', impostor: 'Juez de la corte' },
  { category: 'Roles', civilian: 'Payaso de circo', impostor: 'Político en campaña' },
  { category: 'Roles', civilian: 'Cirujano', impostor: 'Carnicero' },
  { category: 'Roles', civilian: 'Astronauta', impostor: 'Buzo de profundidad' },
  { category: 'Roles', civilian: 'Militar (Soldado)', impostor: 'Jugador de Paintball' },
  { category: 'Roles', civilian: 'Sacerdote', impostor: 'Psicólogo' },
  { category: 'Roles', civilian: 'Bombero', impostor: 'Dragón' },
  { category: 'Roles', civilian: 'Espía', impostor: 'Chismoso del barrio' },
  { category: 'Roles', civilian: 'Arquitecto', impostor: 'Niño con Legos' },
  { category: 'Roles', civilian: 'Director de Cine', impostor: 'Dictador' },
  { category: 'Roles', civilian: 'Mimo', impostor: 'Estatua viviente' },
  { category: 'Roles', civilian: 'Guardaparques', impostor: 'Tarzán' },

  // --- LUGARES Y ESCENARIOS (Similares visualmente) ---
  { category: 'Lugares', civilian: 'Desierto del Sahara', impostor: 'Playa sin mar' },
  { category: 'Lugares', civilian: 'Cine', impostor: 'Platillo Volador (Interior)' },
  { category: 'Lugares', civilian: 'Prisión', impostor: 'Zoológico' },
  { category: 'Lugares', civilian: 'Biblioteca', impostor: 'Cementerio (Silencio)' },
  { category: 'Lugares', civilian: 'Gimnasio', impostor: 'Tortura medieval' },
  { category: 'Lugares', civilian: 'Laboratorio Científico', impostor: 'Cocina de Restaurante' },
  { category: 'Lugares', civilian: 'Estadio lleno', impostor: 'Hormiguero' },
  { category: 'Lugares', civilian: 'Faro en la costa', impostor: 'Torre de vigilancia' },
  { category: 'Lugares', civilian: 'Iglú', impostor: 'Refrigerador (Congelador)' },
  { category: 'Lugares', civilian: 'Laberinto', impostor: 'IKEA' },
  { category: 'Lugares', civilian: 'Barco Pirata', impostor: 'Crucero de lujo' },
  { category: 'Lugares', civilian: 'Túnel', impostor: 'Garganta' },

  // --- NATURALEZA Y UNIVERSO ---
  { category: 'Naturaleza', civilian: 'Agujero Negro', impostor: 'Aspiradora' },
  { category: 'Naturaleza', civilian: 'Tornado', impostor: 'Licuadora girando' },
  { category: 'Naturaleza', civilian: 'Iceberg', impostor: 'Cubo de hielo' },
  { category: 'Naturaleza', civilian: 'Tela de araña', impostor: 'Red de pescar' },
  { category: 'Naturaleza', civilian: 'Colmena de abejas', impostor: 'Edificio de apartamentos' },
  { category: 'Naturaleza', civilian: 'Cueva de murciélagos', impostor: 'Sótano oscuro' },
  { category: 'Naturaleza', civilian: 'Volcán en erupción', impostor: 'Grano en la cara (Espinilla)' },
  { category: 'Naturaleza', civilian: 'Relámpago', impostor: 'Flash de cámara' },
  { category: 'Naturaleza', civilian: 'Arcoíris', impostor: 'Puente de colores' },
  { category: 'Naturaleza', civilian: 'Meteorito', impostor: 'Bola de cañón' },
  { category: 'Naturaleza', civilian: 'Eclipse', impostor: 'Apagón' },

  // --- TRANSPORTE Y MOVIMIENTO ---
  { category: 'Transporte', civilian: 'Submarino', impostor: 'Ballena' },
  { category: 'Transporte', civilian: 'Globo Aerostático', impostor: 'Bombillo flotante' },
  { category: 'Transporte', civilian: 'Tanque de Guerra', impostor: 'Tortuga gigante' },
  { category: 'Transporte', civilian: 'Paracaídas', impostor: 'Diente de León (Semilla)' },
  { category: 'Transporte', civilian: 'Trineo de Santa', impostor: 'Carro de Basura' },
  { category: 'Transporte', civilian: 'Cohete espacial', impostor: 'Fuego artificial' },
  { category: 'Transporte', civilian: 'Bicicleta Tandem (Doble)', impostor: 'Matrimonio' },
  { category: 'Transporte', civilian: 'Segway', impostor: 'Patineta voladora' },
  { category: 'Transporte', civilian: 'Teleférico', impostor: 'Tirolesa (Canopy)' },

  // --- CONCEPTOS ABSTRACTOS Y SITUACIONES ---
  { category: 'Abstracto', civilian: 'Lunes por la mañana', impostor: 'Dolor de muelas' },
  { category: 'Abstracto', civilian: 'Viernes por la tarde', impostor: 'Día de pago' },
  { category: 'Abstracto', civilian: 'Primer beso', impostor: 'Ganar la lotería' },
  { category: 'Abstracto', civilian: 'Resaca (Goma)', impostor: 'Golpe en la cabeza' },
  { category: 'Abstracto', civilian: 'Amor a primera vista', impostor: 'Hechizo mágico' },
  { category: 'Abstracto', civilian: 'Divorcio', impostor: 'Guerra Civil' },
  { category: 'Abstracto', civilian: 'Jubilación', impostor: 'Vacaciones eternas' },
  { category: 'Abstracto', civilian: 'Fama', impostor: 'Estar desnudo en público' },
  { category: 'Abstracto', civilian: 'Secreto', impostor: 'Tesoro enterrado' },
  { category: 'Abstracto', civilian: 'Mentira', impostor: 'Bola de nieve (Crece)' },
  { category: 'Abstracto', civilian: 'Déjà vu', impostor: 'Repetición de TV' },

  // --- OBJETOS DEPORTIVOS Y JUEGOS ---
  { category: 'Deportes', civilian: 'Bate de Beisbol', impostor: 'Garrote de Cavernícola' },
  { category: 'Deportes', civilian: 'Balón de Futbol', impostor: 'Planeta Tierra' },
  { category: 'Deportes', civilian: 'Raqueta de Ping Pong', impostor: 'Espejo de mano' },
  { category: 'Deportes', civilian: 'Canasta de Baloncesto', impostor: 'Basurero de oficina' },
  { category: 'Deportes', civilian: 'Piscina Olímpica', impostor: 'Bañera gigante' },
  { category: 'Deportes', civilian: 'Medalla de Oro', impostor: 'Moneda de Chocolate' },
  { category: 'Deportes', civilian: 'Silbato', impostor: 'Pájaro cantando' },
  { category: 'Deportes', civilian: 'Tablero de Ajedrez', impostor: 'Piso de cocina (Cuadros)' },
  { category: 'Deportes', civilian: 'Dados', impostor: 'Cubos de azúcar' },
  { category: 'Deportes', civilian: 'Castillo de naipes', impostor: 'Castillo de arena' },
  // --- SECCIÓN ESPECIAL: LO NICA (Amplianda) ---
  { category: 'Lo Nica', civilian: 'El Güegüense', impostor: 'El Viejo y la Vieja' },
  { category: 'Lo Nica', civilian: 'Volcán Masaya (Lava)', impostor: 'Volcán Mombacho (Nubes)' },
  { category: 'Lo Nica', civilian: 'Laguna de Apoyo', impostor: 'Laguna de Xiloá' },
  { category: 'Lo Nica', civilian: 'Catedral de León', impostor: 'Palacio Nacional' },
  { category: 'Lo Nica', civilian: 'Rosquillas de Somoto', impostor: 'Cajetas de Masaya' },
  { category: 'Lo Nica', civilian: 'Nacatamal (Domingo)', impostor: 'Vaho (Fines de semana)' },
  { category: 'Lo Nica', civilian: 'Ir al Oriental (Caos)', impostor: 'Ir a Metrocentro (Paseo)' },
  { category: 'Lo Nica', civilian: 'Chocoyos del Volcán', impostor: 'Monos del Zoológico' },
  { category: 'Lo Nica', civilian: 'Beisbol en el Dennis Martínez', impostor: 'Futbol en el Nacional' },
  { category: 'Lo Nica', civilian: 'Hacer la vaca (Colecta)', impostor: 'Invitar la ronda' },
  { category: 'Lo Nica', civilian: 'Chavalo (Niño)', impostor: 'Maje (Amigo/Joven)' },
  { category: 'Lo Nica', civilian: 'Fritanga de barrio', impostor: 'Comidería del mercado' },
  { category: 'Lo Nica', civilian: 'Puerto Salvador Allende', impostor: 'Malecón de Masaya' },
  { category: 'Lo Nica', civilian: 'Sopa de Mondongo', impostor: 'Sopa de Huevo de Toro' },
  { category: 'Lo Nica', civilian: 'Guardabarranco (Pájaro)', impostor: 'Sacuanjoche (Flor)' },
  { category: 'Lo Nica', civilian: 'La Purísima (Gritería)', impostor: 'Rezo del Niño Dios' },
  { category: 'Lo Nica', civilian: 'Pinol de Iguana', impostor: 'Indio Viejo' },
  { category: 'Lo Nica', civilian: 'Cacao helado', impostor: 'Grambicha (Fresco rojo)' },
  { category: 'Lo Nica', civilian: 'Chinelas Rolter', impostor: 'Zapatos Crocs' },
  { category: 'Lo Nica', civilian: 'Bus ruteado (Ruta)', impostor: 'Bus interlocales (Microbús)' },

  // --- TECNOLOGÍA Y MUNDO DIGITAL (Conceptos distintos pero relacionados) ---
  { category: 'Tecnología', civilian: 'Inteligencia Artificial', impostor: 'Realidad Virtual' },
  { category: 'Tecnología', civilian: 'Dron de video', impostor: 'Avión de papel' },
  { category: 'Tecnología', civilian: 'Impresora 3D', impostor: 'Máquina de coser' },
  { category: 'Tecnología', civilian: 'Criptomoneda (Bitcoin)', impostor: 'Billete de Lotería' },
  { category: 'Tecnología', civilian: 'Influencer de TikTok', impostor: 'Presentador de Noticias' },
  { category: 'Tecnología', civilian: 'Hacker', impostor: 'Detective privado' },
  { category: 'Tecnología', civilian: 'Podcast', impostor: 'Programa de Radio AM' },
  { category: 'Tecnología', civilian: 'Photoshop', impostor: 'Maquillaje real' },
  { category: 'Tecnología', civilian: 'Wikipedia', impostor: 'Enciclopedia de libros' },
  { category: 'Tecnología', civilian: 'Teclado Mecánico', impostor: 'Máquina de Escribir' },
  { category: 'Tecnología', civilian: 'Señal de Wifi', impostor: 'Hilo invisible' },
  { category: 'Tecnología', civilian: 'Smartwatch', impostor: 'Brújula' },
  { category: 'Tecnología', civilian: 'Satélite Espacial', impostor: 'Luna llena' },
  { category: 'Tecnología', civilian: 'Robot Aspiradora', impostor: 'Mascota (Perro)' },
  { category: 'Tecnología', civilian: 'Filtro de Instagram', impostor: 'Máscara de Carnaval' },

  // --- FANTASÍA, TERROR Y SCI-FI ---
  { category: 'Ficción', civilian: 'Máquina del Tiempo', impostor: 'Teletransportador' },
  { category: 'Ficción', civilian: 'Sable de Luz (Star Wars)', impostor: 'Varita Mágica (Harry Potter)' },
  { category: 'Ficción', civilian: 'Zombie (Muerto viviente)', impostor: 'Fantasma (Espíritu)' },
  { category: 'Ficción', civilian: 'Vampiro (Chupa sangre)', impostor: 'Mosquito (Zancudo)' },
  { category: 'Ficción', civilian: 'Dragón (Fuego)', impostor: 'Lanzallamas' },
  { category: 'Ficción', civilian: 'Superfuerza', impostor: 'Invisibilidad' },
  { category: 'Ficción', civilian: 'Ojo de Sauron', impostor: 'Cámara de vigilancia' },
  { category: 'Ficción', civilian: 'Escudo del Capitán América', impostor: 'Martillo de Thor' },
  { category: 'Ficción', civilian: 'La Matrix', impostor: 'Un Sueño Lúcido' },
  { category: 'Ficción', civilian: 'Godzilla', impostor: 'King Kong' },
  { category: 'Ficción', civilian: 'Sirena', impostor: 'Buzo profesional' },
  { category: 'Ficción', civilian: 'Centauro', impostor: 'Jinete a caballo' },
  { category: 'Ficción', civilian: 'Casa embrujada', impostor: 'Castillo abandonado' },
  { category: 'Ficción', civilian: 'Espejo mágico', impostor: 'Pantalla de celular' },
  { category: 'Ficción', civilian: 'Poción de amor', impostor: 'Perfume caro' },

  // --- OBJETOS DEL HOGAR (Funciones parecidas, formas distintas) ---
  { category: 'Hogar', civilian: 'Ventilador de techo', impostor: 'Helicóptero' },
  { category: 'Hogar', civilian: 'Lavadora', impostor: 'Licuadora' },
  { category: 'Hogar', civilian: 'Cuna de bebé', impostor: 'Jaula de mascota' },
  { category: 'Hogar', civilian: 'Inodoro', impostor: 'Trono real' },
  { category: 'Hogar', civilian: 'Ducha (Regadera)', impostor: 'Cascada natural' },
  { category: 'Hogar', civilian: 'Alfombra', impostor: 'Césped' },
  { category: 'Hogar', civilian: 'Cortina', impostor: 'Párpado' },
  { category: 'Hogar', civilian: 'Llave', impostor: 'Contraseña' },
  { category: 'Hogar', civilian: 'Basurero', impostor: 'Papelera de reciclaje (PC)' },
  { category: 'Hogar', civilian: 'Vela aromática', impostor: 'Barra de dinamita' },
  { category: 'Hogar', civilian: 'Sartén antiadherente', impostor: 'Raqueta de Tenis' },
  { category: 'Hogar', civilian: 'Almohada', impostor: 'Nube' },
  { category: 'Hogar', civilian: 'Espejo', impostor: 'Gemelo idéntico' },
  { category: 'Hogar', civilian: 'Escalera de mano', impostor: 'Ascensor' },
  { category: 'Hogar', civilian: 'Paraguas', impostor: 'Techo' },

  // --- COMIDA Y SABORES (Engañosos) ---
  { category: 'Comida', civilian: 'Sushi (Pescado crudo)', impostor: 'Taco (Carne cocida)' },
  { category: 'Comida', civilian: 'Huevo duro', impostor: 'Pelota de Golf' },
  { category: 'Comida', civilian: 'Espagueti', impostor: 'Gusanos de goma' },
  { category: 'Comida', civilian: 'Brocoli', impostor: 'Árbol pequeño (Bonsai)' },
  { category: 'Comida', civilian: 'Queso Suizo (Agujeros)', impostor: 'Esponja de baño' },
  { category: 'Comida', civilian: 'Chile picante', impostor: 'Fuego' },
  { category: 'Comida', civilian: 'Cocos', impostor: 'Bolas de Boliche' },
  { category: 'Comida', civilian: 'Pastel de cumpleaños', impostor: 'Piñata' },
  { category: 'Comida', civilian: 'Bebida energética', impostor: 'Café expreso' },
  { category: 'Comida', civilian: 'Algodón de azúcar', impostor: 'Telaraña' },
  { category: 'Comida', civilian: 'Palomitas de maíz', impostor: 'Granizo' },
  { category: 'Comida', civilian: 'Miel de abeja', impostor: 'Pegamento' },
  { category: 'Comida', civilian: 'Baguette (Pan largo)', impostor: 'Bate de beisbol' },

  // --- PROFESIONES Y ROLES (Conflicto de autoridad) ---
  { category: 'Roles', civilian: 'Árbitro de futbol', impostor: 'Juez de la corte' },
  { category: 'Roles', civilian: 'Payaso de circo', impostor: 'Político en campaña' },
  { category: 'Roles', civilian: 'Cirujano', impostor: 'Carnicero' },
  { category: 'Roles', civilian: 'Astronauta', impostor: 'Buzo de profundidad' },
  { category: 'Roles', civilian: 'Militar (Soldado)', impostor: 'Jugador de Paintball' },
  { category: 'Roles', civilian: 'Sacerdote', impostor: 'Psicólogo' },
  { category: 'Roles', civilian: 'Bombero', impostor: 'Dragón' },
  { category: 'Roles', civilian: 'Espía', impostor: 'Chismoso del barrio' },
  { category: 'Roles', civilian: 'Arquitecto', impostor: 'Niño con Legos' },
  { category: 'Roles', civilian: 'Director de Cine', impostor: 'Dictador' },
  { category: 'Roles', civilian: 'Mimo', impostor: 'Estatua viviente' },
  { category: 'Roles', civilian: 'Guardaparques', impostor: 'Tarzán' },

  // --- LUGARES Y ESCENARIOS (Similares visualmente) ---
  { category: 'Lugares', civilian: 'Desierto del Sahara', impostor: 'Playa sin mar' },
  { category: 'Lugares', civilian: 'Cine', impostor: 'Platillo Volador (Interior)' },
  { category: 'Lugares', civilian: 'Prisión', impostor: 'Zoológico' },
  { category: 'Lugares', civilian: 'Biblioteca', impostor: 'Cementerio (Silencio)' },
  { category: 'Lugares', civilian: 'Gimnasio', impostor: 'Tortura medieval' },
  { category: 'Lugares', civilian: 'Laboratorio Científico', impostor: 'Cocina de Restaurante' },
  { category: 'Lugares', civilian: 'Estadio lleno', impostor: 'Hormiguero' },
  { category: 'Lugares', civilian: 'Faro en la costa', impostor: 'Torre de vigilancia' },
  { category: 'Lugares', civilian: 'Iglú', impostor: 'Refrigerador (Congelador)' },
  { category: 'Lugares', civilian: 'Laberinto', impostor: 'IKEA' },
  { category: 'Lugares', civilian: 'Barco Pirata', impostor: 'Crucero de lujo' },
  { category: 'Lugares', civilian: 'Túnel', impostor: 'Garganta' },

  // --- NATURALEZA Y UNIVERSO ---
  { category: 'Naturaleza', civilian: 'Agujero Negro', impostor: 'Aspiradora' },
  { category: 'Naturaleza', civilian: 'Tornado', impostor: 'Licuadora girando' },
  { category: 'Naturaleza', civilian: 'Iceberg', impostor: 'Cubo de hielo' },
  { category: 'Naturaleza', civilian: 'Tela de araña', impostor: 'Red de pescar' },
  { category: 'Naturaleza', civilian: 'Colmena de abejas', impostor: 'Edificio de apartamentos' },
  { category: 'Naturaleza', civilian: 'Cueva de murciélagos', impostor: 'Sótano oscuro' },
  { category: 'Naturaleza', civilian: 'Volcán en erupción', impostor: 'Grano en la cara (Espinilla)' },
  { category: 'Naturaleza', civilian: 'Relámpago', impostor: 'Flash de cámara' },
  { category: 'Naturaleza', civilian: 'Arcoíris', impostor: 'Puente de colores' },
  { category: 'Naturaleza', civilian: 'Meteorito', impostor: 'Bola de cañón' },
  { category: 'Naturaleza', civilian: 'Eclipse', impostor: 'Apagón' },

  // --- TRANSPORTE Y MOVIMIENTO ---
  { category: 'Transporte', civilian: 'Submarino', impostor: 'Ballena' },
  { category: 'Transporte', civilian: 'Globo Aerostático', impostor: 'Bombillo flotante' },
  { category: 'Transporte', civilian: 'Tanque de Guerra', impostor: 'Tortuga gigante' },
  { category: 'Transporte', civilian: 'Paracaídas', impostor: 'Diente de León (Semilla)' },
  { category: 'Transporte', civilian: 'Trineo de Santa', impostor: 'Carro de Basura' },
  { category: 'Transporte', civilian: 'Cohete espacial', impostor: 'Fuego artificial' },
  { category: 'Transporte', civilian: 'Bicicleta Tandem (Doble)', impostor: 'Matrimonio' },
  { category: 'Transporte', civilian: 'Segway', impostor: 'Patineta voladora' },
  { category: 'Transporte', civilian: 'Teleférico', impostor: 'Tirolesa (Canopy)' },

  // --- CONCEPTOS ABSTRACTOS Y SITUACIONES ---
  { category: 'Abstracto', civilian: 'Lunes por la mañana', impostor: 'Dolor de muelas' },
  { category: 'Abstracto', civilian: 'Viernes por la tarde', impostor: 'Día de pago' },
  { category: 'Abstracto', civilian: 'Primer beso', impostor: 'Ganar la lotería' },
  { category: 'Abstracto', civilian: 'Resaca (Goma)', impostor: 'Golpe en la cabeza' },
  { category: 'Abstracto', civilian: 'Amor a primera vista', impostor: 'Hechizo mágico' },
  { category: 'Abstracto', civilian: 'Divorcio', impostor: 'Guerra Civil' },
  { category: 'Abstracto', civilian: 'Jubilación', impostor: 'Vacaciones eternas' },
  { category: 'Abstracto', civilian: 'Fama', impostor: 'Estar desnudo en público' },
  { category: 'Abstracto', civilian: 'Secreto', impostor: 'Tesoro enterrado' },
  { category: 'Abstracto', civilian: 'Mentira', impostor: 'Bola de nieve (Crece)' },
  { category: 'Abstracto', civilian: 'Déjà vu', impostor: 'Repetición de TV' },

  // --- OBJETOS DEPORTIVOS Y JUEGOS ---
  { category: 'Deportes', civilian: 'Bate de Beisbol', impostor: 'Garrote de Cavernícola' },
  { category: 'Deportes', civilian: 'Balón de Futbol', impostor: 'Planeta Tierra' },
  { category: 'Deportes', civilian: 'Raqueta de Ping Pong', impostor: 'Espejo de mano' },
  { category: 'Deportes', civilian: 'Canasta de Baloncesto', impostor: 'Basurero de oficina' },
  { category: 'Deportes', civilian: 'Piscina Olímpica', impostor: 'Bañera gigante' },
  { category: 'Deportes', civilian: 'Medalla de Oro', impostor: 'Moneda de Chocolate' },
  { category: 'Deportes', civilian: 'Silbato', impostor: 'Pájaro cantando' },
  { category: 'Deportes', civilian: 'Tablero de Ajedrez', impostor: 'Piso de cocina (Cuadros)' },
  { category: 'Deportes', civilian: 'Dados', impostor: 'Cubos de azúcar' },
  { category: 'Deportes', civilian: 'Castillo de naipes', impostor: 'Castillo de arena' },


  // --- OBJETOS CON FORMA CILÍNDRICA O ALARGADA ---
  { category: 'Objetos Cilíndricos', civilian: 'Lápiz Labial', impostor: 'Bala' },
  { category: 'Objetos Cilíndricos', civilian: 'Batería (Pila)', impostor: 'Lata de refresco' },
  { category: 'Objetos Cilíndricos', civilian: 'Rodillo de amasar', impostor: 'Bate de béisbol' },
  { category: 'Objetos Cilíndricos', civilian: 'Telescopio', impostor: 'Bazuca' },
  { category: 'Objetos Cilíndricos', civilian: 'Cigarro', impostor: 'Tiza' },
  { category: 'Objetos Cilíndricos', civilian: 'Pajilla (Popote)', impostor: 'Fideo (Espagueti crudo)' },
  { category: 'Objetos Cilíndricos', civilian: 'Vela', impostor: 'Dinamita' },
  { category: 'Objetos Cilíndricos', civilian: 'Termo de café', impostor: 'Extintor de incendios' },
  { category: 'Objetos Cilíndricos', civilian: 'Salchicha', impostor: 'Dedo humano' },
  { category: 'Objetos Cilíndricos', civilian: 'Tubo de ensayo', impostor: 'Florero' },

  // --- OBJETOS REDONDOS O ESFÉRICOS ---
  { category: 'Objetos Redondos', civilian: 'Bola de Boliche', impostor: 'Sandía' },
  { category: 'Objetos Redondos', civilian: 'Pelota de Tenis', impostor: 'Limón' },
  { category: 'Objetos Redondos', civilian: 'Canica', impostor: 'Ojo de vidrio' },
  { category: 'Objetos Redondos', civilian: 'Perla', impostor: 'Diente' },
  { category: 'Objetos Redondos', civilian: 'Globo terráqueo', impostor: 'Pelota de playa' },
  { category: 'Objetos Redondos', civilian: 'Huevo', impostor: 'Jabón ovalado' },
  { category: 'Objetos Redondos', civilian: 'Moneda', impostor: 'Botón' },
  { category: 'Objetos Redondos', civilian: 'Llantas', impostor: 'Donas de chocolate' },
  { category: 'Objetos Redondos', civilian: 'Sartén (Fondo)', impostor: 'Luna llena' },
  { category: 'Objetos Redondos', civilian: 'Bombillo', impostor: 'Pera' },

  // --- OBJETOS CON DIENTES, REJILLAS O AGUJEROS ---
  { category: 'Texturas', civilian: 'Peine', impostor: 'Serrucho' },
  { category: 'Texturas', civilian: 'Rallador de queso', impostor: 'Lija de pared' },
  { category: 'Texturas', civilian: 'Colador', impostor: 'Mosquitero' },
  { category: 'Texturas', civilian: 'Tenedor', impostor: 'Tridente del Diablo' },
  { category: 'Texturas', civilian: 'Esponja', impostor: 'Pan (Migaja)' },
  { category: 'Texturas', civilian: 'Cepillo de dientes', impostor: 'Escobilla de inodoro' },
  { category: 'Texturas', civilian: 'Llave', impostor: 'Sierra pequeña' },
  { category: 'Texturas', civilian: 'Cierre (Zipper)', impostor: 'Vías del tren' },
  { category: 'Texturas', civilian: 'Red de pescar', impostor: 'Hamaca' },
  { category: 'Texturas', civilian: 'Raqueta de tenis', impostor: 'Matamoscas' },

  // --- OBJETOS DE CAJA, PANTALLA O RECTANGULARES ---
  { category: 'Cajas', civilian: 'Microondas', impostor: 'Caja Fuerte' },
  { category: 'Cajas', civilian: 'Refrigeradora', impostor: 'Ataúd (vertical)' },
  { category: 'Cajas', civilian: 'Libro', impostor: 'Ladrillo' },
  { category: 'Cajas', civilian: 'Smartphone', impostor: 'Barra de chocolate' },
  { category: 'Cajas', civilian: 'Tarjeta de Crédito', impostor: 'Naipe (Carta de juego)' },
  { category: 'Cajas', civilian: 'Laptop cerrada', impostor: 'Carpeta escolar' },
  { category: 'Cajas', civilian: 'Maleta de viaje', impostor: 'Lonchera' },
  { category: 'Cajas', civilian: 'Televisor apagado', impostor: 'Pizarra negra' },
  { category: 'Cajas', civilian: 'Billete', impostor: 'Boleto de entrada' },
  { category: 'Cajas', civilian: 'Dominó', impostor: 'Tumba (Lápida)' },

  // --- OBJETOS PUNZANTES O FILOSOS ---
  { category: 'Punzantes', civilian: 'Aguja', impostor: 'Espina de rosa' },
  { category: 'Punzantes', civilian: 'Clavo', impostor: 'Tornillo' },
  { category: 'Punzantes', civilian: 'Tijeras', impostor: 'Pinzas de cangrejo' },
  { category: 'Punzantes', civilian: 'Cuchillo', impostor: 'Bisturí' },
  { category: 'Punzantes', civilian: 'Lanza', impostor: 'Jabalina' },
  { category: 'Punzantes', civilian: 'Flecha', impostor: 'Cursor del mouse' },
  { category: 'Punzantes', civilian: 'Hacha', impostor: 'Guillotina' },
  { category: 'Punzantes', civilian: 'Anzuelo', impostor: 'Signo de interrogación (?)' },

  // --- OBJETOS CON CABLES, CUERDAS O FLEXIBLES ---
  { category: 'Flexibles', civilian: 'Manguera', impostor: 'Serpiente' },
  { category: 'Flexibles', civilian: 'Audífonos (con cable)', impostor: 'Estetoscopio' },
  { category: 'Flexibles', civilian: 'Cinturón', impostor: 'Cinta métrica' },
  { category: 'Flexibles', civilian: 'Látigo', impostor: 'Cola de gato' },
  { category: 'Flexibles', civilian: 'Collar de perlas', impostor: 'Rosario' },
  { category: 'Flexibles', civilian: 'Cordones de zapato', impostor: 'Espagueti cocido' },
  { category: 'Flexibles', civilian: 'Hilo dental', impostor: 'Cuerda de guitarra' },
  { category: 'Flexibles', civilian: 'Resorte', impostor: 'Colochos (Rizos de pelo)' },

  // --- OBJETOS DE USO DIARIO (NICA/GENERAL) ---
  { category: 'Uso Diario', civilian: 'Abanico de pedestal', impostor: 'Hélice de avión' },
  { category: 'Uso Diario', civilian: 'Pana (Tupper)', impostor: 'Sombrero de copa (invertido)' },
  { category: 'Uso Diario', civilian: 'Pichinga (Bidón)', impostor: 'Tanque de gas' },
  { category: 'Uso Diario', civilian: 'Chinela (Chancla)', impostor: 'Raqueta de matar zancudos' },
  { category: 'Uso Diario', civilian: 'Plancha de ropa', impostor: 'Barco de vapor' },
  { category: 'Uso Diario', civilian: 'Paraguas', impostor: 'Antena parabólica' },
  { category: 'Uso Diario', civilian: 'Escoba', impostor: 'Pincel gigante' },
  { category: 'Uso Diario', civilian: 'Trapeador', impostor: 'Peluca desordenada' },
  { category: 'Uso Diario', civilian: 'Espejo de mano', impostor: 'Sartén pequeña' },
  { category: 'Uso Diario', civilian: 'Grapadora', impostor: 'Cocodrilo de juguete' },

  // --- OBJETOS COMPLEJOS / MECÁNICOS ---
  { category: 'Mecánicos', civilian: 'Reloj de pared', impostor: 'Brújula' },
  { category: 'Mecánicos', civilian: 'Cámara fotográfica', impostor: 'Cíclope (Ojo)' },
  { category: 'Mecánicos', civilian: 'Dron', impostor: 'Mosquito gigante' },
  { category: 'Mecánicos', civilian: 'Calculadora', impostor: 'Control remoto' },
  { category: 'Mecánicos', civilian: 'Llave inglesa', impostor: 'Hueso' },
  { category: 'Mecánicos', civilian: 'Candado', impostor: 'Bolso de mano' },
  { category: 'Mecánicos', civilian: 'Motosierra', impostor: 'Tiburón mecánico' },
  { category: 'Mecánicos', civilian: 'Semáforo', impostor: 'Paleta de helado tricolor' },
  { category: 'Mecánicos', civilian: 'Ancla', impostor: 'Gancho de ropa' },

  { category: 'Hogar', civilian: 'Alfombra', impostor: 'Césped' },
  { category: 'Hogar', civilian: 'Cortina', impostor: 'Párpado' },
  { category: 'Hogar', civilian: 'Silla', impostor: 'Trono' },
  { category: 'Hogar', civilian: 'Cama', impostor: 'Hamaca' },
  { category: 'Hogar', civilian: 'Puerta', impostor: 'Libro' },
  { category: 'Hogar', civilian: 'Ventana', impostor: 'Pantalla de TV' },
  { category: 'Hogar', civilian: 'Techo', impostor: 'Sombrero' },
  { category: 'Hogar', civilian: 'Piso', impostor: 'Suela de zapato' },
  { category: 'Hogar', civilian: 'Pared', impostor: 'Frontera' },
  { category: 'Hogar', civilian: 'Llave', impostor: 'Contraseña' },
  { category: 'Hogar', civilian: 'Candado', impostor: 'Boca cerrada' },
  { category: 'Hogar', civilian: 'Escalera', impostor: 'Jirafa' },
  { category: 'Hogar', civilian: 'Timbre', impostor: 'Notificación de celular' },
  { category: 'Hogar', civilian: 'Basurero', impostor: 'Agujero negro' },
  { category: 'Hogar', civilian: 'Espejo', impostor: 'Gemelo malvado' },

  { category: 'Objetos', civilian: 'Peine', impostor: 'Esqueleto de pescado' },
  { category: 'Objetos', civilian: 'Botón', impostor: 'Ombligo' },
  { category: 'Objetos', civilian: 'Cierre (Zíper)', impostor: 'Cicatriz' },
  { category: 'Objetos', civilian: 'Aguja', impostor: 'Mosquito' },
  { category: 'Objetos', civilian: 'Hilo', impostor: 'Cabello' },
  { category: 'Objetos', civilian: 'Tijeras', impostor: 'Cangrejo' },
  { category: 'Objetos', civilian: 'Lija', impostor: 'Lengua de gato' },
  { category: 'Objetos', civilian: 'Esponja', impostor: 'Pulmón' },
  { category: 'Objetos', civilian: 'Jabón', impostor: 'Hielo' },
  { category: 'Objetos', civilian: 'Toalla', impostor: 'Perro mojado' },
  { category: 'Objetos', civilian: 'Perfume', impostor: 'Flor' },
  { category: 'Objetos', civilian: 'Reloj', impostor: 'Corazón (Latido)' },
  { category: 'Objetos', civilian: 'Billetera', impostor: 'Banco' },
  { category: 'Objetos', civilian: 'Mochila', impostor: 'Caparazón de tortuga' },
  { category: 'Objetos', civilian: 'Paraguas', impostor: 'Hongo' },

  { category: 'Comida', civilian: 'Pizza', impostor: 'Rueda' },
  { category: 'Comida', civilian: 'Espagueti', impostor: 'Gusanos' },
  { category: 'Comida', civilian: 'Huevo', impostor: 'Cero (Número 0)' },
  { category: 'Comida', civilian: 'Queso', impostor: 'Luna' },
  { category: 'Comida', civilian: 'Pan', impostor: 'Piedra' },
  { category: 'Comida', civilian: 'Salchicha', impostor: 'Dedo' },
  { category: 'Comida', civilian: 'Maíz', impostor: 'Dientes' },
  { category: 'Comida', civilian: 'Cebolla', impostor: 'Ogro (Shrek)' },
  { category: 'Comida', civilian: 'Nuez', impostor: 'Cerebro' },
  { category: 'Comida', civilian: 'Chocolate', impostor: 'Lodo' },
  { category: 'Comida', civilian: 'Helado', impostor: 'Nieve' },
  { category: 'Comida', civilian: 'Pastel', impostor: 'Castillo' },
  { category: 'Comida', civilian: 'Café', impostor: 'Petróleo' },
  { category: 'Comida', civilian: 'Leche', impostor: 'Pintura blanca' },
  { category: 'Comida', civilian: 'Limón', impostor: 'Ojo cerrado (por lo ácido)' },

  { category: 'Naturaleza', civilian: 'Árbol', impostor: 'Brócoli gigante' },
  { category: 'Naturaleza', civilian: 'Raíz', impostor: 'Rayo' },
  { category: 'Naturaleza', civilian: 'Hoja', impostor: 'Panel solar' },
  { category: 'Naturaleza', civilian: 'Tronco', impostor: 'Columna' },
  { category: 'Naturaleza', civilian: 'Flor', impostor: 'Antena parabólica' },
  { category: 'Naturaleza', civilian: 'Río', impostor: 'Carretera' },
  { category: 'Naturaleza', civilian: 'Montaña', impostor: 'Pirámide' },
  { category: 'Naturaleza', civilian: 'Volcán', impostor: 'Grano (Espinilla)' },
  { category: 'Naturaleza', civilian: 'Cueva', impostor: 'Boca' },
  { category: 'Naturaleza', civilian: 'Isla', impostor: 'Lunar' },
  { category: 'Naturaleza', civilian: 'Desierto', impostor: 'Playa sin mar' },
  { category: 'Naturaleza', civilian: 'Nube', impostor: 'Humo' },
  { category: 'Naturaleza', civilian: 'Estrella', impostor: 'Diamante' },
  { category: 'Naturaleza', civilian: 'Sol', impostor: 'Foco' },
  { category: 'Naturaleza', civilian: 'Viento', impostor: 'Fantasma' },

  { category: 'Animales', civilian: 'Cebra', impostor: 'Paso peatonal' },
  { category: 'Animales', civilian: 'Jirafa', impostor: 'Grúa' },
  { category: 'Animales', civilian: 'Elefante', impostor: 'Aspiradora' },
  { category: 'Animales', civilian: 'Tortuga', impostor: 'Casco militar' },
  { category: 'Animales', civilian: 'Erizo', impostor: 'Cepillo de pelo' },
  { category: 'Animales', civilian: 'Serpiente', impostor: 'Cuerda' },
  { category: 'Animales', civilian: 'Pájaro', impostor: 'Avión' },
  { category: 'Animales', civilian: 'Pez', impostor: 'Submarino' },
  { category: 'Animales', civilian: 'Mariposa', impostor: 'Hada' },
  { category: 'Animales', civilian: 'Luciérnaga', impostor: 'Dron' },
  { category: 'Animales', civilian: 'Gato', impostor: 'Ninja' },
  { category: 'Animales', civilian: 'Perro', impostor: 'Mejor amigo' },
  { category: 'Animales', civilian: 'Loro', impostor: 'Grabadora de voz' },
  { category: 'Animales', civilian: 'Camaleón', impostor: 'Semáforo' },
  { category: 'Animales', civilian: 'Mono', impostor: 'Niño travieso' },

  { category: 'Ciudad', civilian: 'Edificio', impostor: 'Caja de cereal' },
  { category: 'Ciudad', civilian: 'Carretera', impostor: 'Río de asfalto' },
  { category: 'Ciudad', civilian: 'Semáforo', impostor: 'Árbol de navidad' },
  { category: 'Ciudad', civilian: 'Poste de luz', impostor: 'Jirafa de metal' },
  { category: 'Ciudad', civilian: 'Alcantarilla', impostor: 'Portal secreto' },
  { category: 'Ciudad', civilian: 'Parque', impostor: 'Bosque miniatura' },
  { category: 'Ciudad', civilian: 'Escuela', impostor: 'Fábrica de cerebros' },
  { category: 'Ciudad', civilian: 'Hospital', impostor: 'Taller de humanos' },
  { category: 'Ciudad', civilian: 'Cementerio', impostor: 'Dormitorio' },
  { category: 'Ciudad', civilian: 'Cine', impostor: 'Cueva oscura' },
  { category: 'Ciudad', civilian: 'Tienda', impostor: 'Bodega' },
  { category: 'Ciudad', civilian: 'Restaurante', impostor: 'Comedor de casa' },
  { category: 'Ciudad', civilian: 'Gimnasio', impostor: 'Tortura voluntaria' },
  { category: 'Ciudad', civilian: 'Biblioteca', impostor: 'Wikipedia física' },
  { category: 'Ciudad', civilian: 'Aeropuerto', impostor: 'Estación de buses' },

  { category: 'Aleatorio', civilian: 'Fuego', impostor: 'Ira' },
  { category: 'Aleatorio', civilian: 'Hielo', impostor: 'Indiferencia' },
  { category: 'Aleatorio', civilian: 'Máscara', impostor: 'Mentira' },
  { category: 'Aleatorio', civilian: 'Globo', impostor: 'Pulmón' },
  { category: 'Aleatorio', civilian: 'Piñata', impostor: 'Víctima' },
  { category: 'Aleatorio', civilian: 'Regalo', impostor: 'Soborno' },
  { category: 'Aleatorio', civilian: 'Bomba', impostor: 'Sorpresa' },
  { category: 'Aleatorio', civilian: 'Mapa', impostor: 'Laberinto' },
  { category: 'Aleatorio', civilian: 'Brújula', impostor: 'Reloj' },
  { category: 'Aleatorio', civilian: 'Imán', impostor: 'Carisma' },
  { category: 'Aleatorio', civilian: 'Batería', impostor: 'Energía' },
  { category: 'Aleatorio', civilian: 'Enchufe', impostor: 'Nariz de cerdo' },
  { category: 'Aleatorio', civilian: 'Cable', impostor: 'Vena' },
  { category: 'Aleatorio', civilian: 'Antena', impostor: 'Oreja' },
  { category: 'Aleatorio', civilian: 'Robot', impostor: 'Zombie' }


];

// Nota: wordCategories y WordCategory deprecados; mantenidos sólo si algún código legado los importa.
export const wordCategories = {} as Record<string, string[]>;
export type WordCategory = string;